Traceback (most recent call last):
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jnapolitano/venvs/finance/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def naive_query_passengers_by_month():
    query_string = """
        SELECT date_trunc(dropoff_datetime,MONTH) as Month,
        sum(passenger_count) as Sum_PASS,
        sum(total_amount) as TOTAL_AMOUNT_SUM
        FROM `nyc-tlc.green.trips_2015` 
        where dropoff_datetime BETWEEN '2015-02-01' AND '2015-04-30'
        GROUP BY Month;
        """

    result = query_big_query(query_string = query_string)

    return result.to_dataframe()
naive_df = naive_query_passengers_by_month()    
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mDefaultCredentialsError[0m                   Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     11[0m     result [38;5;241m=[39m query_big_query(query_string [38;5;241m=[39m query_string)
[1;32m     13[0m     [38;5;28;01mreturn[39;00m result[38;5;241m.[39mto_dataframe()
[0;32m---> 14[0m naive_df [38;5;241m=[39m [43mnaive_query_passengers_by_month[49m[43m([49m[43m)[49m

Input [0;32mIn [3][0m, in [0;36mnaive_query_passengers_by_month[0;34m()[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mnaive_query_passengers_by_month[39m():
[1;32m      2[0m     query_string [38;5;241m=[39m [38;5;124m"""[39m
[1;32m      3[0m [38;5;124m        SELECT date_trunc(dropoff_datetime,MONTH) as Month,[39m
[1;32m      4[0m [38;5;124m        sum(passenger_count) as Sum_PASS,[39m
[0;32m   (...)[0m
[1;32m      8[0m [38;5;124m        GROUP BY Month;[39m
[1;32m      9[0m [38;5;124m        [39m[38;5;124m"""[39m
[0;32m---> 11[0m     result [38;5;241m=[39m [43mquery_big_query[49m[43m([49m[43mquery_string[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mquery_string[49m[43m)[49m
[1;32m     13[0m     [38;5;28;01mreturn[39;00m result[38;5;241m.[39mto_dataframe()

Input [0;32mIn [2][0m, in [0;36mquery_big_query[0;34m(query_string)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mquery_big_query[39m(query_string):
[0;32m----> 2[0m     client [38;5;241m=[39m [43mbigquery[49m[38;5;241;43m.[39;49m[43mClient[49m[43m([49m[43m)[49m
[1;32m      3[0m     query_job [38;5;241m=[39m client[38;5;241m.[39mquery(query_string)
[1;32m      5[0m     results [38;5;241m=[39m query_job[38;5;241m.[39mresult()  [38;5;66;03m# Waits for job to complete.[39;00m

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/cloud/bigquery/client.py:226[0m, in [0;36mClient.__init__[0;34m(self, project, credentials, _http, location, default_query_job_config, client_info, client_options)[0m
[1;32m    216[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m(
[1;32m    217[0m     [38;5;28mself[39m,
[1;32m    218[0m     project[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    224[0m     client_options[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    225[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[0;32m--> 226[0m     [38;5;28;43msuper[39;49m[43m([49m[43mClient[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m
[1;32m    227[0m [43m        [49m[43mproject[49m[38;5;241;43m=[39;49m[43mproject[49m[43m,[49m
[1;32m    228[0m [43m        [49m[43mcredentials[49m[38;5;241;43m=[39;49m[43mcredentials[49m[43m,[49m
[1;32m    229[0m [43m        [49m[43mclient_options[49m[38;5;241;43m=[39;49m[43mclient_options[49m[43m,[49m
[1;32m    230[0m [43m        [49m[43m_http[49m[38;5;241;43m=[39;49m[43m_http[49m[43m,[49m
[1;32m    231[0m [43m    [49m[43m)[49m
[1;32m    233[0m     kw_args [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mclient_info[39m[38;5;124m"[39m: client_info}
[1;32m    234[0m     bq_host [38;5;241m=[39m _get_bigquery_host()

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/cloud/client/__init__.py:320[0m, in [0;36mClientWithProject.__init__[0;34m(self, project, credentials, client_options, _http)[0m
[1;32m    319[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, project[38;5;241m=[39m[38;5;28;01mNone[39;00m, credentials[38;5;241m=[39m[38;5;28;01mNone[39;00m, client_options[38;5;241m=[39m[38;5;28;01mNone[39;00m, _http[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 320[0m     [43m_ClientProjectMixin[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mproject[49m[38;5;241;43m=[39;49m[43mproject[49m[43m,[49m[43m [49m[43mcredentials[49m[38;5;241;43m=[39;49m[43mcredentials[49m[43m)[49m
[1;32m    321[0m     Client[38;5;241m.[39m[38;5;21m__init__[39m(
[1;32m    322[0m         [38;5;28mself[39m, credentials[38;5;241m=[39mcredentials, client_options[38;5;241m=[39mclient_options, _http[38;5;241m=[39m_http
[1;32m    323[0m     )

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/cloud/client/__init__.py:268[0m, in [0;36m_ClientProjectMixin.__init__[0;34m(self, project, credentials)[0m
[1;32m    265[0m     project [38;5;241m=[39m [38;5;28mgetattr[39m(credentials, [38;5;124m"[39m[38;5;124mproject_id[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m    267[0m [38;5;28;01mif[39;00m project [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 268[0m     project [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_determine_default[49m[43m([49m[43mproject[49m[43m)[49m
[1;32m    270[0m [38;5;28;01mif[39;00m project [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    271[0m     [38;5;28;01mraise[39;00m [38;5;167;01mEnvironmentError[39;00m(
[1;32m    272[0m         [38;5;124m"[39m[38;5;124mProject was not passed and could not be [39m[38;5;124m"[39m
[1;32m    273[0m         [38;5;124m"[39m[38;5;124mdetermined from the environment.[39m[38;5;124m"[39m
[1;32m    274[0m     )

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/cloud/client/__init__.py:287[0m, in [0;36m_ClientProjectMixin._determine_default[0;34m(project)[0m
[1;32m    284[0m [38;5;129m@staticmethod[39m
[1;32m    285[0m [38;5;28;01mdef[39;00m [38;5;21m_determine_default[39m(project):
[1;32m    286[0m     [38;5;124;03m"""Helper:  use default project detection."""[39;00m
[0;32m--> 287[0m     [38;5;28;01mreturn[39;00m [43m_determine_default_project[49m[43m([49m[43mproject[49m[43m)[49m

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py:152[0m, in [0;36m_determine_default_project[0;34m(project)[0m
[1;32m    140[0m [38;5;124;03m"""Determine default project ID explicitly or implicitly as fall-back.[39;00m
[1;32m    141[0m 
[1;32m    142[0m [38;5;124;03mSee :func:`google.auth.default` for details on how the default project[39;00m
[0;32m   (...)[0m
[1;32m    149[0m [38;5;124;03m:returns: Default project if it can be determined.[39;00m
[1;32m    150[0m [38;5;124;03m"""[39;00m
[1;32m    151[0m [38;5;28;01mif[39;00m project [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 152[0m     _, project [38;5;241m=[39m [43mgoogle[49m[38;5;241;43m.[39;49m[43mauth[49m[38;5;241;43m.[39;49m[43mdefault[49m[43m([49m[43m)[49m
[1;32m    153[0m [38;5;28;01mreturn[39;00m project

File [0;32m~/venvs/finance/lib/python3.9/site-packages/google/auth/_default.py:579[0m, in [0;36mdefault[0;34m(scopes, request, quota_project_id, default_scopes)[0m
[1;32m    571[0m             _LOGGER[38;5;241m.[39mwarning(
[1;32m    572[0m                 [38;5;124m"[39m[38;5;124mNo project ID could be determined. Consider running [39m[38;5;124m"[39m
[1;32m    573[0m                 [38;5;124m"[39m[38;5;124m`gcloud config set project` or setting the [39m[38;5;132;01m%s[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    574[0m                 [38;5;124m"[39m[38;5;124menvironment variable[39m[38;5;124m"[39m,
[1;32m    575[0m                 environment_vars[38;5;241m.[39mPROJECT,
[1;32m    576[0m             )
[1;32m    577[0m         [38;5;28;01mreturn[39;00m credentials, effective_project_id
[0;32m--> 579[0m [38;5;28;01mraise[39;00m exceptions[38;5;241m.[39mDefaultCredentialsError(_HELP_MESSAGE)

[0;31mDefaultCredentialsError[0m: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

